/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import ServiceLayer.UserCatalog;
import ServiceLayer.UserException;
import business.User;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Brasha
 */
public class ApproveReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private User user;
    private UserCatalog fdb;
    private ArrayList<User> LR;
    Vector<String> elements;
    
    
    public ApproveReqJPanel(User us) {
        initComponents();
        setBounds(10,20,250,300);
        user =us;
        fdb = new UserCatalog();
        try {
            LR = fdb.getRequestTo(user);
        } catch (UserException ex) {
            Logger.getLogger(ApproveReqJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        int size = LR.size();
        elements = new Vector<String>();
        for(int i=0;i<size;i++)
        {
            elements.add(String.valueOf(LR.get(i).getID()) + " " + LR.get(i).getFirstName() + " " + LR.get(i).getLastName());
        }
        
        jList1.setListData(elements);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jButton2.setText("Отклонить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Добавить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(elements.size()>0)
        {
            try {
                fdb.deleteRequest(user, LR.get(jList1.getSelectedIndex()));
            } catch (UserException ex) {
                Logger.getLogger(ApproveReqJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            LR.remove(jList1.getSelectedIndex());
            elements.remove(jList1.getSelectedIndex());
            
            updateElements();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(elements.size() > 0)
        {
        user.addFriend((LR.get(jList1.getSelectedIndex())));
        try {
            System.out.println(user.getID()+" "+LR.get(jList1.getSelectedIndex()).getID());
            fdb.approveRequest(user, LR.get(jList1.getSelectedIndex()));
            JOptionPane.showMessageDialog(null, "Заявка принята!", "Успех", 1);
        } catch (UserException ex) {
            JOptionPane.showMessageDialog(null, "Ошибка при добавлении заявки!", "Ошибка", 1);
        }
        
        updateElements();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void updateElements()
    {
        elements.clear();
        try {
            LR = fdb.getRequestTo(user);
        } catch (UserException ex) {
            Logger.getLogger(ApproveReqJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        int size = LR.size();
        for(int i=0;i<size;i++)
        {
            elements.add(String.valueOf(LR.get(i).getID()) + " " + LR.get(i).getFirstName() + " " + LR.get(i).getLastName());
        }
        jList1.setListData(elements);
        jList1.updateUI();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
