/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import business.PrivateMessage;
import business.User;
import db.DataDBException;
import db.MessagesDBWorker;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Brasha
 */
public class CreateMessageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMessageJPanel
     */
    
    private User user;
    private User to;
    private MessagesDBWorker mdb;
    private ArrayList<PrivateMessage> LM;
    
    public CreateMessageJPanel() {
        initComponents();
        setBounds(10,20,280,280);
    }
    
    public void SetContent(User from, User toto)
    {
        user =from;
        to = toto;
        mdb = new MessagesDBWorker();
        try {
            LM = mdb.GetPrivateMessageTo(user.getID());
        } catch (DataDBException ex) {
            JOptionPane.showMessageDialog(null, "Ошибка при создании сообщения!", "Ошибка", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sendButton1.setText("Отправить");
        sendButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addComponent(sendButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(sendButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButton1ActionPerformed
        try {
            mdb.insertPrivateMessage(user, to, jTextArea1.getText());
            JOptionPane.showMessageDialog(null, "Сообщение успешно отправлено!", "Успех!", 1);
        } catch (DataDBException ex) {
            JOptionPane.showMessageDialog(null, "Сообщение не может быть отправлено!", "Ошибка!", 1);
        }
    }//GEN-LAST:event_sendButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton sendButton1;
    // End of variables declaration//GEN-END:variables
}
